inputs:
  CHART_PATH:
    description: "Path to the chart to package"
    required: true
  CHART_NAME:
    description: "Name of the chart to package"
    required: true

name: Package
description: Package a chart
runs:
  using: composite
  steps:
    - name: Base Earthly action
      uses: ./.github/actions/earthly/base
    - uses: "actions/checkout@v4"
      with:
        fetch-depth: 0
    - name: Package
      shell: bash
      env:
        CHART_PATH: ${{ inputs.CHART_PATH }}
      run: >
        earthly $CHART_PATH+package
    - name: Archive chart
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.CHART_NAME }}_${{ github.ref_type == 'branch' && github.sha || github.ref_name }}.tgz
        path: ${{ inputs.CHART_PATH }}/*.tgz
