apiVersion: v2
name: regions
description: Formance Private Regions Helm Chart
home: "https://formance.com"
sources:
- "https://github.com/formancehq/operator"
- "https://github.com/formancehq/agent"
- "https://github.com/formancehq/helm/charts/regions"

maintainers:
- name: "Formance Team"
  email: "support@formance.com"
icon: "https://avatars.githubusercontent.com/u/84325077?s=200&v=4"

type: application
version: 2.11.4
appVersion: "latest"

dependencies:
- name: agent
  version: 2.X
  repository: "file://../agent"
  condition: agent.enabled
- name: operator
  version: v2.7.0
  repository: "oci://ghcr.io/formancehq/helm"
  condition: operator.enabled
