apiVersion: v2
name: regions
description: Formance Private Regions Helm Chart
home: "https://formance.com"
sources:
  - "https://github.com/formancehq/operator"
  - "https://github.com/formancehq/agent"
maintainers:
  - name: "Formance Team"
    email: "support@formance.com"
icon: "https://avatars.githubusercontent.com/u/84325077?s=200&v=4"

type: application
version: "v2.5.4"
appVersion: "latest"

dependencies:
  - name: agent
    version: v2.3.2
    repository: "file://../agent"
    condition: agent.enabled
  - name: operator
    version: v2.3.1
    repository: "oci://ghcr.io/formancehq/helm"
    condition: operator.enabled
