VERSION --wildcard-builds --wildcard-copy 0.8

IMPORT .. AS charts

schema:
  FROM charts+schema-base
  WORKDIR /src
  DO --pass-args charts+SCHEMA

readme:
  FROM charts+readme-base
  WORKDIR /src/core
  COPY --dir (+sources/*) .
  DO --pass-args charts+README_GENERATOR

sources:
  DO --pass-args charts+BASE
  WORKDIR /src/core
  COPY (+schema/*) .
  DO --pass-args charts+SOURCES

validate:
  FROM +dependencies
  RUN echo "No validation required"

dependencies:
  FROM +sources
  WORKDIR /src/core
  DO --pass-args charts+DEPENDENCIES

lint:
  FROM +dependencies
  WORKDIR /src/core
  DO --pass-args charts+LINT

package:
  FROM +lint
  WORKDIR /src/core
  DO --pass-args charts+PACKAGE
