{{- if and .Values.config.job.stackLifeCycle.enabled .Values.global.nats.enabled (not .Values.feature.managedStacks) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "core.fullname" . }}-stack-lc
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  suspend: {{ .Values.config.job.stackLifeCycle.suspend }}
  # timeZone: "europe/paris"    # Depending of kubernetes v1.27
  schedule: {{ .Values.config.job.stackLifeCycle.schedule | quote }}
  startingDeadlineSeconds: {{ .Values.config.job.stackLifeCycle.startingDeadlineSeconds }}
  concurrencyPolicy: {{ .Values.config.job.stackLifeCycle.concurrencyPolicy }}
  jobTemplate:
    metadata:
      labels:
        {{- include "core.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          serviceAccountName:  {{ include "core.serviceAccountName" . }}
          restartPolicy: {{ .Values.config.job.stackLifeCycle.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "core.fullname" . }}
              {{- with .Values.config.job.stackLifeCycle.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              args:
                - stack-cycle
                - --dry-run={{ .Values.config.stack.cycle.dryRun }}
              env:
                - name: STACK_WARN_DELAY
                  value: "{{.Values.config.stack.cycle.delay.warn}}"
                - name: STACK_DISPOSABLE_DELAY
                  value: "{{.Values.config.stack.cycle.delay.disposable}}"
                - name: SERVICE_URL
                  value: "{{ .Values.global.scheme }}://{{ .Values.global.serviceHost }}/api"
                {{- include "core.postgres.uri" . | nindent 16 }}
                {{- include "core.env.common" . | nindent 16 }}
                {{- include "core.nats.env" . | nindent 16 }}
                {{- include "core.monitoring" . | nindent 16 }}
                {{- with .Values.additionalEnv }}
                {{- tpl (toYaml .) $ }}
                {{- end }}
              resources:
                {{- toYaml .Values.config.job.stackLifeCycle.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.config.job.stackLifeCycle.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.config.job.stackLifeCycle.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}