apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "core.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "core.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "core.fullname" . }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      {{- if gt (len .Values.initContainers) 0 }}
        {{ .Values.initContainers | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
          {{- with .Values.volumeMounts }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          env:
            {{- include "membership.env" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            {{- if and (not .Values.feature.managedStacks) .Values.global.nats.enabled }}
            - name: grpc
              containerPort: 8082
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /_healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /_healthcheck
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
