apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "core.fullname" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
  {{- with .Values.config.migration.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "core.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - storage
            - migrations
            - up
          env:
            - name: DEBUG
              value: "{{.Values.debug}}"
            - name: DEV
              value: "{{.Values.dev}}"
            {{- include "core.postgres.uri" . | nindent 12 }}
        {{- if .Values.global.nats.enabled }}
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - stream
            - init
          env:
          - name: JETSTREAM_REPLICAS
            value: "{{ .Values.config.publisher.jetstream.replicas }}"
          {{- include "core.env.common" . | nindent 10 }}
          {{- include "core.nats.env" . | nindent 10 }}
        {{- end }}