{{- if .Values.config.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "core.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
  {{- with merge .Values.config.migration.annotations (include "migrations.job.annotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.config.migration.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "core.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "membership.job.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.config.migration.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - storage
            - migrations
            - up
          env:
            - name: DEV
              value: "{{.Values.dev}}"
            {{- include "core.env.common" . | nindent 12 }}
            {{- include "core.monitoring" . | nindent 12 }}
            {{- include "job.postgres.uri" . | nindent 12 }}
            {{- include "core.licence.env" . | nindent 12 }}
        {{- if .Values.global.nats.enabled }}
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.config.migration.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - stream
            - init
          env:
          - name: JETSTREAM_REPLICAS
            value: "{{ .Values.config.publisher.jetstream.replicas }}"
          {{- include "core.licence.env" . | nindent 10 }}
          {{- include "core.env.common" . | nindent 10 }}
          {{- include "core.nats.env" . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.config.migration.volumes}}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}