{{- if .Values.config.migration.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "membership.job.serviceAccountName" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
  {{- with .Values.config.migration.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
