VERSION 0.8

IMPORT ../ AS root
IMPORT ../core AS core

schema:
  FROM root+schema-base
  WORKDIR /src
  DO --pass-args root+SCHEMA

readme:
  FROM root+readme-base
  WORKDIR /src/demo
  COPY --dir (+dependencies/*) .
  DO --pass-args root+README_GENERATOR

sources:
  DO --pass-args root+BASE
  WORKDIR /src/demo
  COPY (+schema/*) .
  DO --pass-args root+SOURCES

dependencies:
  FROM +sources
  WORKDIR /src/demo
  DO --pass-args root+DEPENDENCIES

validate:
  FROM +dependencies
  WORKDIR /src/demo
  COPY (+readme/*) .
  DO --pass-args root+VALIDATE

package:
  FROM +validate
  WORKDIR /src/demo
  DO --pass-args root+PACKAGE


