nats:
  enabled: false
  fullnameOverride: nats
  config:
    cluster:
      enabled: true
      replicas: 3
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: false
          size: 20Gi

postgresql:
  enabled: true
  fullnameOverride: postgresql
  architecture: standalone
  global:
    postgresql:
      auth:
        username: formance
        password: formance
        database: formance
        postgresPassword: formance
  primary:
    persistence:
      enabled: false

opensearch:
  enabled: false
  fullnameOverride: opensearch
  security:
    enabled: false
  master:
    replicaCount: 1
    persistence:
      enabled: false
  data:
    replicaCount: 2
    persistence:
      enabled: false
  coordinating:
    replicaCount: 0
  ingest:
    enabled: false
    replicaCount: 0
  dashboards:
    enabled: true