VERSION 0.8

IMPORT ../console AS console
IMPORT ../membership AS membership
IMPORT ../portal AS portal
IMPORT ../core AS core
IMPORT .. AS root

# svgs:
#   FROM minlag/mermaid-cli
#   COPY --dir build /data
#   RUN mkdir -p /data/svg
#   RUN /home/mermaidcli/node_modules/.bin/mmdc -p /puppeteer-config.json -i /data/build/mmd/controlplane.mmd -o /data/svg/controlplane.svg --configFile /data/build/config.json
#   SAVE ARTIFACT /data/svg/controlplane.svg AS LOCAL ./controlplane.svg

schema:
  FROM root+schema-base
  WORKDIR /src
  DO --pass-args root+SCHEMA

readme:
  FROM root+readme-base
  WORKDIR /src/core
  COPY --dir (core+dependencies/*) .
  
  WORKDIR /src/console
  COPY --dir (console+dependencies/*) .
  WORKDIR /src/membership
  COPY --dir (membership+dependencies/*) .
  WORKDIR /src/portal
  COPY --dir (portal+dependencies/*) .

  WORKDIR /src/cloudprem
  COPY (+dependencies/*) .
  COPY (+schema/*) .
  # COPY (+svgs/*) .
  COPY *.gotmpl .
  DO --pass-args root+README_GENERATOR
sources:
  DO --pass-args root+BASE
  WORKDIR /src/cloudprem
  COPY --dir profiles .
  COPY (+schema/*) .
  DO --pass-args root+SOURCES

dependencies:
  FROM +sources
  WORKDIR /src/console
  COPY --dir (console+dependencies/*) .
  WORKDIR /src/membership
  COPY --dir (membership+dependencies/*) .
  WORKDIR /src/portal
  COPY --dir (portal+dependencies/*) .
  WORKDIR /src/cloudprem
  DO --pass-args root+DEPENDENCIES

validate:
  FROM +dependencies
  WORKDIR /src/cloudprem
  COPY (+readme/*) .
  DO --pass-args root+VALIDATE

package:
  FROM +validate
  WORKDIR /src/cloudprem
  DO --pass-args root+PACKAGE

publish:
  FROM +package
  WORKDIR /src/cloudprem
  DO --pass-args root+PUBLISH
