{{- if and .Values.dex.enabled .Values.dex.configSecret.createConfigSecretOverrides }}
{{ $defaultValues :=  (include "dex-values" . ) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: membership-dex-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
stringData:
  config.yaml: |-
    {{- tpl ((merge .Values.dex.configOverrides $defaultValues)|toYaml) . | nindent 6 }}
{{- end }}