apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: configuration
data:
  {{- include "identity.configData" . | nindent 2 }}
