{{- if and .Values.hooks.serviceAccount.create (or .Values.hooks.migration.enabled .Values.hooks.bootstrap.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity.hookServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: hooks
  annotations:
    {{- include "identity.hookAnnotations" . | nindent 4 }}
    helm.sh/hook-weight: "0"
    {{- with .Values.hooks.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}
