inputs:
  CHART_NAME:
    required: true
    description: "Name of the chart to package"
  CHART_DIR:
    required: true
    description: "Path to the chart to package"
    default: ".helm"

name: AnyChart
description: AnyChart workflow

runs:
  using: composite
  steps:
    - name: Validate
      uses: ./.github/actions/helm/validate
      with:
        CHART_PATH: ./${{ inputs.CHART_DIR }}/${{ inputs.CHART_NAME }}
    - name: Dirty
      uses: ./.github/actions/github/dirty
    - name: Package
      uses: ./.github/actions/helm/package
      with:
        CHART_NAME: ${{ inputs.CHART_NAME }}
        CHART_PATH: ./${{ inputs.CHART_DIR }}/${{ inputs.CHART_NAME }}
