apiVersion: v2
name: search
description: Formance Search Helm Chart
home: "https://formance.com"
sources:
  - "https://github.com/formancehq/control"
maintainers:
  - name: "Formance Team"
    email: "support@formance.com"
icon: "https://avatars.githubusercontent.com/u/84325077?s=200&v=4"
type: application
version: 1.1.0
appVersion: "v0.4.0"
