apiVersion: v2
name: gateway
description: Formance Gateway Helm Chart
type: application
home: "https://formance.com"
maintainers:
  - name: "Formance Team"
    email: "support@formance.com"
icon: "https://avatars.githubusercontent.com/u/84325077?s=200&v=4"
version: 1.2.0
appVersion: "10.24.0"
dependencies:
  - name: traefik
    version: 20.8.0
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
  - name: cert-manager
    version: v1.7.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled