apiVersion: v2
name: control
description: A Helm chart for Kubernetes
home: "https://formance.com"
sources:
  - "https://github.com/formancehq/control"
maintainers:
  - name: "Formance Team"
    email: "support@formance.com"
icon: "https://avatars.githubusercontent.com/u/84325077?s=200&v=4"
type: application
version: 1.1.0
appVersion: "v1.3.0-rc.4"
