VERSION --wildcard-builds --wildcard-copy 0.8

IMPORT github.com/formancehq/earthly:tags/v0.16.3 AS core
IMPORT .. AS root

BASE:
  FUNCTION
  FROM core+base-image
  RUN apk update && apk add openssl helm

ARTIFACT:
  FUNCTION
  SAVE ARTIFACT --if-exists ./Chart.lock AS LOCAL ./
  SAVE ARTIFACT ./Chart.yaml AS LOCAL ./
  SAVE ARTIFACT --if-exists ./values.yaml AS LOCAL ./
  SAVE ARTIFACT --if-exists ./values.schema.json AS LOCAL ./
  SAVE ARTIFACT --if-exists ./README.md AS LOCAL ./
  SAVE ARTIFACT --if-exists ./templates AS LOCAL ./
  SAVE ARTIFACT --if-exists ./charts AS LOCAL ./
  SAVE ARTIFACT --if-exists ./profiles AS LOCAL ./
  SAVE ARTIFACT --if-exists ./LICENCE AS LOCAL ./

SOURCES:
  FUNCTION
  COPY (root+sources/* --PATH=LICENSE) .
  COPY --if-exists Chart.lock .
  COPY Chart.yaml .
  COPY --if-exists values.yaml .
  COPY --dir --if-exists templates .
  DO --pass-args +ARTIFACT

VALIDATE:
  FUNCTION
  DO --pass-args +LINT
  DO --pass-args +TEMPLATE
  DO --pass-args +ARTIFACT

LINT:
  FUNCTION
  ARG additionalArgs
  RUN helm lint ./ --strict $additionalArgs

TEMPLATE:
  FUNCTION
  RUN helm template ./ $additionalArgs

DEPENDENCIES:
  FUNCTION
  RUN helm dependencies update
  DO --pass-args +ARTIFACT

PACKAGE:
  FUNCTION
  RUN helm package .
  SAVE ARTIFACT ./*.tgz AS LOCAL ./

README_GENERATOR:
  FUNCTION
  RUN helm-docs --chart-search-root=.. --document-dependency-values
  SAVE ARTIFACT README.md AS LOCAL README.md

readme-base:
  DO --pass-args +BASE
  RUN apk add go
  ENV GOPATH /go
  ENV GOTOOLCHAIN=local
  ARG GOCACHE=/go-cache
  ARG GOMODCACHE=/go-mod-cache
  ARG HELM_DOCS_VERSION=v1.14
  ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
  DO --pass-args core+GO_INSTALL --package=github.com/norwoodj/helm-docs/cmd/helm-docs@$HELM_DOCS_VERSION

SCHEMA:
  FUNCTION
  COPY values.yaml .
  RUN helm schema -input values.yaml -output values.schema.json
  SAVE ARTIFACT ./values.schema.json AS LOCAL ./

schema-base:
  DO --pass-args +BASE
  RUN apk add --no-cache git
  RUN helm plugin install https://github.com/losisin/helm-values-schema-json.git
