VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.16.2 AS core

helm-sources:
    ARG --required PROJECT
    FROM core+helm-base
    WORKDIR /src/helm
    COPY --dir ./$PROJECT/* /src/helm
    SAVE ARTIFACT /src/helm

helm-readme-generator:
    ARG --required PROJECT
    FROM node:20
    WORKDIR /src/readme-generator-for-helm
    GIT CLONE git@github.com:bitnami/readme-generator-for-helm.git .
    RUN npm install
    WORKDIR /src/helm
    COPY --pass-args (+helm-sources/*) .
    RUN node /src/readme-generator-for-helm/bin/index.js --values values.yaml --schema values.schema.json --readme README.md
    SAVE ARTIFACT README.md AS LOCAL ./$PROJECT/README.md
    
helm-validate:
    ARG --required PROJECT
    FROM +helm-sources --PROJECT=$PROJECT
    RUN apk add --no-cache git
    RUN helm plugin install https://github.com/losisin/helm-values-schema-json.git
    WORKDIR /src/helm
    RUN helm dependencies update
    RUN helm lint ./ --strict
    RUN helm schema -input values.yaml -output values.schema.json
    SAVE ARTIFACT /src/helm AS LOCAL ./$PROJECT

helm-package:
    ARG --required PROJECT
    FROM +helm-sources --PROJECT=$PROJECT
    WORKDIR /src/helm
    RUN helm package . --destination /src/build/
    SAVE ARTIFACT /src/build

helm-publish:
    ARG --required PROJECT
    FROM +helm-package --PROJECT=$PROJECT
    WORKDIR /src/build
    WITH DOCKER
        RUN --secret GITHUB_TOKEN echo $GITHUB_TOKEN | docker login ghcr.io -u NumaryBot --password-stdin
    END
    WITH DOCKER
        RUN helm push ./*.tgz oci://ghcr.io/formancehq/helm
    END