global:
  # -- Enable debug mode
  # @section -- Global configuration
  debug: false
  # -- is the base domain for portal and console
  # @section -- Global configuration
  serviceHost: ""

  platform:
    console:
      # -- is the scheme for the console
      # @section -- Global configuration
      scheme: "https"
      # -- is the host for the console
      # @section -- Global configuration
      host: "console.{{ .Values.global.serviceHost }}"
    portal:
      # -- is the scheme for the portal
      # @section -- Global configuration
      scheme: "https"
      # -- is the host for the portal
      # @section -- Global configuration
      host: "portal.{{ .Values.global.serviceHost }}"
    cookie:
      # -- is used to encrypt a cookie that share authentication between platform services (console, portal, ...),is used to store the current state organizationId-stackId
      # @section -- Global configuration
      encryptionKey: "changeMe00"
      # -- is the name of the secret
      # @section -- Global configuration
      existingSecret: ""
      # -- is the key contained within the secret
      # @section -- Global configuration
      secretKeys:
        encryptionKey: ""

    membership:
      # -- is the scheme for the membership
      # @section -- Global configuration
      scheme: "https"
      # -- is the host for the membership
      # @section -- Global configuration
      host: "membership.{{ .Values.global.serviceHost }}"

      oauthClient:
        # -- is the id of the client
        # @section -- Global configuration
        id: "platform"
        # -- is the secret of the client
        # @section -- Global configuration
        secret: "changeMe1"
        # -- is the name of the secret
        # @section -- Global configuration
        existingSecret: ""
        # -- is the key contained within the secret
        # @section -- Global configuration
        secretKeys:
          secret: ""

# -- Number of replicas
replicas: 1

serviceAccount:
  # -- Service account creation
  create: true
  # -- Service account name
  name: ""
  # -- Service account annotations
  annotations: {}

image:
  # -- image repository
  repository: ghcr.io/formancehq/console
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 9431e5f4b4b1a03cb8f02ef1676507b9c023f2bb

# -- Console resources
resources:
  {}
  # requests:
  #   cpu: 250m
  #   memory: 512Mi
  # limits:
  #   cpu: 500m
  #   memory: 2048Mi

# -- Console readiness probe
readinessProbe: {}

# -- Console liveness probe
livenessProbe: {}

service:
  # -- service annotations
  annotations: {}
  # -- service type
  type: ClusterIP
  # -- service cluster IP
  clusterIP: ""
  ports:
    # -- service http port
    http:
      port: 3000
      # -- service node port
      # nodePort:

ingress:
  # -- ingress enabled
  enabled: true
  # -- ingress class name
  className: ""
  # -- ingress annotations
  annotations: {}
  hosts:
    # -- ingress host
    - host: "{{ tpl .Values.global.platform.console.host $ }}"
      paths:
        - # -- ingress path
          path: /
          # -- ingress path type
          pathType: Prefix
  # -- ingress tls
  tls:
    []
    # -- ingress tls secret name
    # - secretName: YOUR_TLS_SECRET_NAME

# -- Console volume mounts
volumeMounts: []

# -- Console volumes
volumes: []

# -- Console node selector
nodeSelector: {}

# -- Console tolerations
tolerations: []

# -- Console affinity
affinity: {}

config:
  # -- Console environment
  environment: production
  # -- Console additional environment variables
  additionalEnv:
    {}
    # -- Console additional environment variables HOST
    # HOST: "0.0.0.0"
    # -- Console additional environment variables FEATURE_DISABLED
    # FEATURE_DISABLED: ""

  # -- Otel collector configuration
  monitoring:
    traces:
      # -- Console monitoring traces enabled
      enabled: false
      # -- Console monitoring traces url
      url: ""
      # -- Console monitoring traces port
      port: 4317
      # -- Console monitoring traces attributes
      attributes: ""
