name: Pre-Commit
description: Run pre-commit checks with Earthly
runs:
  using: composite
  steps:
    - name: Base Earthly action
      uses: ./.github/actions/earthly/base
    - name: PreCommit
      shell: bash
      run: >
        earthly +pre-commit
