# Before all:
# This chart use only 1 db user account, you might to have separated user for dex/membership. You are allowed to bind any secret and override the default config under .membership.dex.configOverrides with template
#
# Make sure to create the following secret within the release namespace:
# - platform
# - membership
# - postgresql-credentials
# - portal
# You will be able to rename them accordingly
#

global:
  platform:
    cookie:
      existingSecret: "platform"
      secretKeys:
        encryptionKey: "encryption-key"
    membership:
      oauthClient:
        existingSecret: "platform"
        secretKeys:
          secret: "membership-oauth-client-secret"

  postgresql:
    auth:
      existingSecret: "postgresql-credentials"
      secretKeys:
        adminPasswordKey: "admin-password"
        userPasswordKey: "admin-password"

portal:
  config:
    cookie:
      existingSecret: "portal-secrets"
      secretKeys:
        secret: "portal-cookie-secret"

membership:
  config:
    oidc:
      existingSecret: "membership"
      secretKeys:
        secret: "dex-client-secret"
  dex:
    envVars:
      - name: MEMBERSHIP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: "membership"
            key: "dex-client-secret"
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "postgresql-credentials"
            key: "admin-password"
