membership:
  global:
    nats:
      enabled: true
      url: "nats://${PUBLISHER_NATS_USERNAME}:${PUBLISHER_NATS_PASSWORD}@nats.{{ .Release.Namespace }}.svc:4222"
      auth:
        user:
        password:
        existingSecret: ""
        secretKeys:
          password: password
          username: username
