{{- if and .Values.global.licence.createSecret .Values.global.licence.token }}
{{- $secretName := .Values.global.licence.existingSecret | default (printf "%s-licence" .Release.Name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "formance.labels" . | nindent 4 }}
    formance.com/stack: any
stringData:
  token: {{ .Values.global.licence.token | quote }}
  issuer: {{ .Values.global.licence.issuer | quote }}
{{- end }}
