---
apiVersion: formance.com/v1beta1
kind: Stack
metadata:
  name: formance-dev
spec:
  versionsFromFile: v2.0
---
apiVersion: formance.com/v1beta1
kind: Gateway
metadata:
  name: formance-dev
spec:
  stack: formance-dev
---
apiVersion: formance.com/v1beta1
kind: Ledger
metadata:
  name: formance-dev
spec:
  stack: formance-dev
---
apiVersion: formance.com/v1beta1
kind: Payments
metadata:
  name: formance-dev
spec:
  stack: formance-dev
