name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Tests
        run: earthly +ci
      - name: Get changed files
        id: changed-files
        shell: bash
        run: |
          hasChanged=$(git status --porcelain) 
          if (( $(echo ${#hasChanged}) != 0 )); then
            git status
            echo "There are changes in the repository"
            exit 1
          fi
  
  release:
    name: Release
    needs:
      - tests
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release
        run: earthly +release 
        env:
          EARTHLY_SECRETS: "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"