name: Publish
on:
  release:
    types: [published]
jobs:
  push:
    runs-on: shipfox-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Nix
        uses: ./.github/actions/default
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - id: download-release-asset
        name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{github.ref_name}}"
          file: ${{github.ref_name}}.tgz
          target: ${{github.ref_name}}.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
        run: nix develop --impure --command just helm-publish ${{github.ref_name}}.tgz
