VERSION --wildcard-builds --wildcard-copy 0.8

IMPORT ../ AS charts
IMPORT ../core AS core

schema:
  FROM charts+schema-base
  WORKDIR /src
  DO --pass-args charts+SCHEMA

readme:
  FROM charts+readme-base
  WORKDIR /src/agent
  COPY --dir (+dependencies/*) .
  DO --pass-args charts+README_GENERATOR

sources:
  DO --pass-args charts+BASE
  WORKDIR /src/agent
  COPY (+schema/*) .
  DO --pass-args charts+SOURCES

dependencies:
  FROM +sources
  WORKDIR /src/agent
  DO --pass-args charts+DEPENDENCIES

validate:
  FROM +dependencies
  WORKDIR /src/agent
  COPY (+readme/*) .
  DO --pass-args charts+VALIDATE

package:
  FROM +validate
  WORKDIR /src/agent
  DO --pass-args charts+PACKAGE
